DROP DATABASE IF EXISTS demodb;

DROP ROLE IF EXISTS demo; 

CREATE ROLE demo LOGIN
  ENCRYPTED PASSWORD 'md568cefad35fed037c318b1e44cc3480cf' -- password: pass
  NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE;

CREATE DATABASE demodb WITH OWNER = demo ENCODING = 'UTF8';